# Generated by Django 5.2 on 2025-07-10 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_rate_source',
            field=models.CharField(choices=[('USER', 'User-defined'), ('XE', 'XE.com'), ('RC_A', 'Remittance Center A')], default='XE', max_length=20),
        ),
    ]
