# Generated by Django 5.2 on 2025-08-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_preferred_rate_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="preferred_rate_source",
        ),
    ]
