# Generated by Django 5.2 on 2025-08-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_preferred_rate_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="base_currency",
        ),
    ]
