# Generated by Django 5.2 on 2025-06-24 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisitions', '0001_initial'),
        ('entities', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_owner', models.CharField(blank=True, max_length=255)),
                ('person_insured', models.CharField(blank=True, max_length=255)),
                ('insurance_type', models.CharField(choices=[('term', 'Term'), ('whole', 'Whole'), ('health', 'Health'), ('vul', 'VUL')], max_length=10)),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=18)),
                ('premium_mode', models.CharField(choices=[('annual', 'Annual'), ('semiannual', 'Semi-Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], max_length=20)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_balance', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=10)),
                ('acquisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='acquisitions.acquisition')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='entities.entity')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_insurance',
            },
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='insurance.insurance')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_payments', to='transactions.transaction')),
            ],
            options={
                'db_table': 'insurance_premiumpayment',
            },
        ),
    ]
