# Generated by Django 5.2 on 2025-06-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0003_acquisition_sum_assured_amount'),
        ('entities', '0006_alter_entity_entity_type'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='name',
        ),
        migrations.AddField(
            model_name='insurance',
            name='acquisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='acquisitions.acquisition'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='person_insured',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_owner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
