# Generated by Django 5.2 on 2025-06-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurance_name_insurance_acquisition_and_more'),
        ('transactions', '0014_alter_categorytag_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_payments', to='transactions.transaction'),
        ),
    ]
