# Generated by Django 5.2 on 2025-06-17 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0001_initial'),
        ('transactions', '0009_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('product', 'Product'), ('stock_bond', 'Stock/Bond'), ('property', 'Property'), ('insurance', 'Insurance')], default='product', max_length=20)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('market', models.CharField(blank=True, max_length=100)),
                ('is_sellable', models.BooleanField(blank=True, null=True)),
                ('expected_lifespan_years', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('insurance_type', models.CharField(blank=True, choices=[('vul', 'VUL'), ('term', 'Term'), ('whole', 'Whole'), ('health', 'Health')], max_length=10)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_tx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_purchase', to='transactions.transaction')),
                ('sell_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_sale', to='transactions.transaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acquisitions_acquisition',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
