# Generated by Django 5.2 on 2025-06-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='model_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='target_selling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='category',
            field=models.CharField(choices=[('product', 'Product'), ('stock_bond', 'Stock/Bond'), ('property', 'Property'), ('insurance', 'Insurance'), ('equipment', 'Equipment'), ('vehicle', 'Vehicle')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='is_sellable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
