# Generated by Django 5.2 on 2025-06-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0002_acquisition_mileage_acquisition_model_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='sum_assured_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
