# Generated by Django 5.2 on 2025-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0002_remove_acquisition_maturity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='provider',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
