# Generated by Django 5.2 on 2025-06-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0003_acquisition_sum_assured_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='is_sellable',
        ),
    ]
