# Generated by Django 5.2 on 2025-06-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0004_remove_acquisition_is_sellable'),
        ('transactions', '0014_alter_categorytag_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='purchase_tx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_purchase', to='transactions.transaction'),
        ),
    ]
