# Generated by Django 5.2 on 2025-06-08 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_alter_transactiontemplate_autopop_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_tx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_purchase', to='transactions.transaction')),
                ('sell_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sale', to='transactions.transaction')),
            ],
        ),
    ]
