# Generated by Django 5.2 on 2025-06-27 11:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lender',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='lender_name_ci_unique'),
        ),
    ]
