# Generated by Django 5.2 on 2025-06-27 12:09

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0002_lender_lender_name_ci_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lender',
            name='lender_name_ci_unique',
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to='liabilities.lender'),
        ),
        migrations.AddConstraint(
            model_name='lender',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_issuer_name_ci'),
        ),
    ]
