# Generated by Django 5.2 on 2025-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liabilities", "0006_creditcard_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="loan",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
