# Generated by Django 5.2 on 2025-09-02 22:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0007_creditcard_currency_loan_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='current_balance',
            new_name='available_credit',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
