# Generated by Django 5.2 on 2025-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Banks', 'Banks'), ('E-Wallet', 'E-Wallet'), ('Cash', 'Cash-on-Hand'), ('Outside', 'Outside')], max_length=50),
        ),
    ]
