# Generated by Django 5.2 on 2025-07-11 12:25

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_currency_alter_account_account_type"),
        ("currencies", "0003_alter_exchangerate_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("account_name"),
                models.F("user"),
                condition=models.Q(("is_active", True)),
                name="uniq_account_name_user_active_ci",
            ),
        ),
    ]
