# Generated by Django 5.2 on 2025-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('USER', 'User-defined'), ('FRANKFURTER', 'Frankfurter'), ('REM_A', 'Remittance Center A')], max_length=20),
        ),
    ]
