# Generated by Django 5.2 on 2025-08-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0003_alter_exchangerate_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("currency_from", "currency_to")},
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="source",
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="user",
        ),
    ]
