# Generated by Django 5.2 on 2025-05-06 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('transaction_type_source', models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=20, null=True)),
                ('transaction_type_destination', models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=20, null=True)),
                ('asset_type_source', models.CharField(blank=True, choices=[('Liquid', 'Liquid'), ('Non-Liquid', 'Non-Liquid'), ('Expenses', 'Expenses')], max_length=20, null=True)),
                ('asset_type_destination', models.CharField(blank=True, choices=[('Liquid', 'Liquid'), ('Non-Liquid', 'Non-Liquid'), ('Expenses', 'Expenses')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('account_destination', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_destination', to='accounts.account')),
                ('account_source', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_as_source', to='accounts.account')),
                ('entity_destination', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_entity_destination', to='entities.entity')),
                ('entity_source', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_entity_source', to='entities.entity')),
            ],
        ),
    ]
