# Generated by Django 5.2 on 2025-05-24 23:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('autopop_map', models.JSONField(default=dict, help_text='Example: {"transtype_source": "Income", "assettype_destination": "Liquid", "account_destination": "Cash-on-Hand"}')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type_destination',
            field=models.CharField(blank=True, choices=[('liquid', 'Liquid'), ('non-liquid', 'Non-Liquid'), ('outside', 'Outside')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type_source',
            field=models.CharField(blank=True, choices=[('liquid', 'Liquid'), ('non-liquid', 'Non-Liquid'), ('outside', 'Outside')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type_destination',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('buy asset', 'Buy Asset'), ('sell asset', 'Sell Asset'), ('transfer', 'Transfer'), ('outside', 'Outside')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type_source',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('buy asset', 'Buy Asset'), ('sell asset', 'Sell Asset'), ('transfer', 'Transfer'), ('outside', 'Outside')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Which template (if any) was applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transactiontemplate'),
        ),
    ]
