# Generated by Django 5.2 on 2025-05-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactiontemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('buy asset', 'Buy Asset'), ('sell asset', 'Sell Asset'), ('transfer', 'Transfer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type_destination',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type_source',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type_destination',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type_source',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
