# Generated by Django 5.2 on 2025-06-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_amount_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontemplate',
            name='autopop_map',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
