# Generated by Django 5.2 on 2025-09-03 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_system_hidden"),
        ("transactions", "0006_fill_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categorytag",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="categorytag",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_tags",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("premium_payment", "Premium Payment"),
                    ("buy acquisition", "Buy Acquisition"),
                    ("sell acquisition", "Sell Acquisition"),
                    ("transfer", "Transfer"),
                    ("loan_disbursement", "Loan Disbursement"),
                    ("loan_repayment", "Loan Repayment"),
                    ("cc_purchase", "Cc Purchase"),
                    ("cc_payment", "Cc Payment"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categorytag",
            unique_together={("user", "transaction_type", "name", "account")},
        ),
    ]
