# Generated by Django 5.2 on 2025-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_user_transactiontemplate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('buy product', 'Buy Product'), ('sell product', 'Sell Product'), ('transfer', 'Transfer')], max_length=20, null=True),
        ),
    ]
