# Generated by Django 5.2 on 2025-09-03 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_system_hidden'),
        ('transactions', '0007_alter_categorytag_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytag',
            unique_together={('user', 'transaction_type', 'name', 'entity')},
        ),
        migrations.AddField(
            model_name='categorytag',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_tags', to='entities.entity'),
        ),
        migrations.RemoveField(
            model_name='categorytag',
            name='account',
        ),
    ]
