# Generated by Django 5.2 on 2025-09-03 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _drop_old_entity_column(apps, schema_editor):
    """Drop stale entity column created by earlier migrations."""
    CategoryTag = apps.get_model('transactions', 'CategoryTag')
    table = CategoryTag._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        columns = [col.name for col in connection.introspection.get_table_description(cursor, table)]
        if 'entity_id' in columns:
            cursor.execute(f'ALTER TABLE {table} DROP COLUMN entity_id')

class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_entity_system_hidden'),
        ('transactions', '0007_alter_categorytag_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytag',
            unique_together=set(),
        ),
        migrations.RunPython(
            code=_drop_old_entity_column,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RenameField(
            model_name='categorytag',
            old_name='account',
            new_name='entity',
        ),
        migrations.AlterField(
            model_name='categorytag',
            name='entity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='category_tags',
                to='entities.entity',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='categorytag',
            unique_together={('user', 'transaction_type', 'name', 'entity')},
        ),
    ]
