# Generated by Django 5.2 on 2025-06-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('buy product', 'Buy Product'), ('sell product', 'Sell Product'), ('buy property', 'Buy Property'), ('sell property', 'Sell Property'), ('transfer', 'Transfer')], max_length=20, null=True),
        ),
    ]
