# Generated by Django 5.2 on 2025-06-18 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_type'),
        ('entities', '0006_alter_entity_entity_type'),
        ('transactions', '0011_categorytag_transaction_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_source'], name='transaction_account_3916db_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account_destination'], name='transaction_account_0a490c_idx'),
        ),
    ]
