# Generated by Django 5.2 on 2025-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transaction_transaction_account_3916db_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytag',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('buy_acquisition', 'Buy Acquisition'), ('sell_acquisition', 'Sell Acquisition')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('buy acquisition', 'Buy Acquisition'), ('sell acquisition', 'Sell Acquisition'), ('transfer', 'Transfer')], max_length=20, null=True),
        ),
    ]
