# Generated by Django 5.2 on 2025-05-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('account', 'Account'), ('investment', 'Investment'), ('emergency Fund', 'Emergency Fund'), ('business Fund', 'Business Fund'), ('retirement Fund', 'Retirement Fund'), ('educational Fund', 'Educational Fund'), ('outside', 'Outside'), ('others', 'Others')], max_length=50),
        ),
    ]
