# Generated by Django 5.2 on 2025-06-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_add_fixed_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_account_entity',
            field=models.BooleanField(default=False),
        ),
    ]
