# Generated by Django 5.2 on 2025-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_entity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
