# Generated by Django 5.2 on 2025-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_create_default_outside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('free fund', 'Free Fund'), ('investment fund', 'Investment Fund'), ('emergency Fund', 'Emergency Fund'), ('business Fund', 'Business Fund'), ('retirement Fund', 'Retirement Fund'), ('educational Fund', 'Educational Fund'), ('outside', 'Outside'), ('others', 'Others')], max_length=50),
        ),
    ]
