# Generated by Django 5.2 on 2025-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_entity_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('free fund', 'Free Fund'), ('investment fund', 'Investment Fund'), ('emergency fund', 'Emergency Fund'), ('business fund', 'Business Fund'), ('retirement fund', 'Retirement Fund'), ('educational fund', 'Educational Fund'), ('outside', 'Outside'), ('personal fund', 'Personal Fund')], max_length=50),
        ),
    ]
